FROM alpine:3.20@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d AS build
RUN apk add perl gmp-dev mpc1-dev mpfr-dev elfutils-dev bash flex bison pahole \
            sed mawk diffutils findutils zstd python3 gcc curl make musl-dev \
            squashfs-tools linux-headers openssl openssl-dev
COPY . /build
RUN adduser -s /bin/sh -D build
RUN chown -R build:build /build
USER build
WORKDIR /build
RUN chmod +x hack/build/docker-build-internal.sh
