[project]
name = "linux-kernel-oci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Marly Salazar", email = "marly@edera.dev" }
]
requires-python = ">=3.14"
dependencies = [
    "packaging>=26.3",
    "pyyaml>=6.0.3",
]

[project.scripts]
linux-kernel-oci = "linux_kernel_oci:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black==26.5.1",
]

[tool.uv]
package = false
