#!/bin/sh

if [ -z "${KERNEL_VERSION}" ]
then
  echo "ERROR: KERNEL_VERSION not specified." >> /dev/stderr
  exit 1
fi

KERNEL_MAJOR="$(echo "${KERNEL_VERSION}" | awk -F '.' '{print $1}')"
KERNEL_SRC_URL="https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_MAJOR}.x/linux-${KERNEL_VERSION}.tar.xz"
