name: Test Kernel Build
on:
  pull_request:
  push:
    branches:
    - main
permissions:
  contents: read
  packages: read
jobs:
  test:
    uses: ./.github/workflows/matrix.yml
    with:
      spec: "only-latest:flavor=host,zone,zone-nvidiagpu"
      publish: false
