name: Test Kernel Build
on:
  pull_request:
  push:
    branches:
    - main
permissions:
  contents: read
  packages: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/matrix.yml
    with:
      spec: "only-latest-lts:flavor=host,zone,zone-nvidiagpu"
      publish: false
