name: Test Kernel Build
on:
  pull_request:
  push:
    branches:
    - main
permissions:
  contents: read
  packages: read
env:
  TEST_MATRIX_SPEC: "only-latest:flavor=zone"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        submodules: recursive
    - name: install dependencies
      run: ./hack/build/install-matrix-deps.sh
    - name: generate spec-new matrix
      run: 'PATH="${HOME}/go/bin:${PATH}" KERNEL_BUILD_SPEC="new" ./hack/build/generate-matrix.sh'
    - name: upload spec-new matrix
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      with:
        name: spec-new-matrix
        path: "matrix.json"
        compression-level: 0
    - name: generate spec-rebuild matrix
      run: 'PATH="${HOME}/go/bin:${PATH}" KERNEL_BUILD_SPEC="rebuild" ./hack/build/generate-matrix.sh'
    - name: upload spec-rebuild matrix
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      with:
        name: spec-rebuild-matrix
        path: "matrix.json"
        compression-level: 0
    - name: generate test matrix
      run: 'PATH="${HOME}/go/bin:${PATH}" ./hack/build/generate-matrix.sh "${TEST_MATRIX_SPEC}"'
    - name: upload test matrix
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      with:
        name: test-matrix
        path: "matrix.json"
        compression-level: 0
    - name: docker setup linux-kernel-oci
      run: sudo python3 ./hack/build/docker-setup.py
    - name: docker setup buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3
    - name: docker login ghcr.io
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        registry: ghcr.io
        username: "${{github.actor}}"
        password: "${{secrets.GITHUB_TOKEN}}"
    - name: generate docker script
      run: "./hack/build/generate-docker-script.sh matrix.json"
    - name: upload docker script
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      with:
        name: "docker.sh"
        path: "docker.sh"
        compression-level: 0
    - name: run docker script
      run: sh -x docker.sh
