name: Test Kernel Build
on:
  pull_request:
  push:
    branches:
    - main
permissions:
  contents: read
  packages: read
env:
  TEST_MATRIX_SPEC: "only-latest:flavor=zone-amdgpu"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      FIRMWARE_URL: "https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-20250410.tar.xz"
      FIRMWARE_SIG_URL: "https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-20250410.tar.sign"
      KERNEL_ARCHITECTURES: "x86_64"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        submodules: recursive
    - name: install dependencies
      run: ./hack/build/install-matrix-deps.sh
    - name: generate spec-new matrix
      run: 'PATH="${HOME}/go/bin:${PATH}" KERNEL_BUILD_SPEC="new" ./hack/build/generate-matrix.sh'
    - name: upload spec-new matrix
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: spec-new-matrix
        path: "matrix.json"
        compression-level: 0
    - name: generate spec-rebuild matrix
      run: 'PATH="${HOME}/go/bin:${PATH}" KERNEL_BUILD_SPEC="rebuild" ./hack/build/generate-matrix.sh'
    - name: upload spec-rebuild matrix
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: spec-rebuild-matrix
        path: "matrix.json"
        compression-level: 0
    - name: generate test matrix
      run: 'PATH="${HOME}/go/bin:${PATH}" ./hack/build/generate-matrix.sh "${TEST_MATRIX_SPEC}"'
    - name: upload test matrix
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: test-matrix
        path: "matrix.json"
        compression-level: 0
    - name: docker setup linux-kernel-oci
      run: sudo python3 ./hack/build/docker-setup.py
    - name: docker setup buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
    - name: docker login ghcr.io
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        registry: ghcr.io
        username: "${{github.actor}}"
        password: "${{secrets.GITHUB_TOKEN}}"
    - name: generate docker script
      run: "./hack/build/generate-docker-script.sh matrix.json"
    - name: upload docker script
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: "docker.sh"
        path: "docker.sh"
        compression-level: 0
    - name: run docker script
      run: sh -x docker.sh
